spring:
  cloud:
    ##===== consul configuration =====##
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: false

    ##===== gateway rules =====##
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #-----------------------------------#
        - id: hypervisor_route
          uri: lb://ABEILLE-BASIC-HYPERVISOR
          predicates:
            - Path=/hypervisor/{segment}
          filters:
            - StripPrefix= 1

        #-----------------------------------#
        - id: assets_route
          uri: lb://ABEILLE-BASIC-ASSETS
          predicates:
            - Path=/assets/{segment}
          filters:
            - StripPrefix= 1

        #-----------------------------------#
        - id: server_route
          uri: lb://ABEILLE-SECURE-SERVER
          predicates:
            - Path=/server/{segment}
          filters:
            - StripPrefix= 1