##===== server port =====##
server:
  port: 8760
  http2:
    enabled: true

##===== active profiles =====##
spring:
  profiles:
    active: dev

  application:
    name: abeille-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowCredentials: true
            allowedMethods:
              - OPTIONS
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        #-----------------------------------#
        - id: hypervisor_route
          uri: lb://hypervisor
          predicates:
            - Path=/hypervisor/**
          filters:
            - StripPrefix= 1

        #-----------------------------------#
        - id: assets_route
          uri: lb://assets
          predicates:
            - Path=/assets/**
          filters:
            - StripPrefix= 1