##===== server port =====##
server:
  port: 80

##===== active profiles =====##
spring:
  profiles:
    active: dev

  application:
    name: abeille-gateway

  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: false