spring:
  cloud:
    ##===== consul configuration =====##
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: false

    ##===== gateway rules =====##
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
        #-----------------------------------#
        - id: hypervisor_route
          uri: lb://abeille-basic-hypervisor
          predicates:
            - Path=/hypervisor/{segment}
          filters:
            - StripPrefix= 1

        #-----------------------------------#
        - id: assets_route
          uri: lb://abeille-basic-assets
          predicates:
            - Path=/assets/{segment},/assets/oauth/{segment}
          filters:
            - StripPrefix= 1