##===== server port =====##
server:
  port: 80

##===== active profiles =====##
spring:
  profiles:
    active: prod

  application:
    name: abeille-gateway

  cloud:
    consul:
      host: 122.152.218.103
      port: 8500
      discovery:
        register: false