##===== server port =====##
server:
  port: 80

##===== active profiles =====##
spring:
  profiles:
    active: prod

  application:
    name: abeille-gateway

  cloud:
    consul:
      discovery:
        register: false