##===== load Eureka registry center =====##
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

##===== server port =====##
server:
  port: 80

##===== application name =====##
spring:
  application:
    name: abeille-gateway
  ##===== routing configuration =====##
  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        #-----------------------------------#
        - id: host_route
          uri: lb://abeille-basic
          predicates:
            - Path=/basic
          filters:
            - RewritePath=/basic/(?<segment>.*), /$\{segment}
          #-----------------------------------#
        - id: host_route
          uri: http://127.0.0.1:8761
          predicates:
            - Path=/eureka
        #-----------------------------------#
        - id: host_route
          uri: lb://abeille-business
          predicates:
            - Path=/business