spring:
  cloud:
    ##===== consul configuration =====##
    consul:
      host: 192.168.31.100
      port: 8500
      discovery:
        register: false

    ##===== gateway rules =====##
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        #-----------------------------------#
        - id: hypervisor_route
          uri: lb://abeille-basic-hypervisor
          predicates:
            - Path=/hypervisor/**
          filters:
            - StripPrefix= 1

        #-----------------------------------#
        - id: assets_route
          uri: lb://abeille-basic-assets
          predicates:
            - Path=/assets/**
          filters:
            - StripPrefix= 1

        #-----------------------------------#
        - id: server_route
          uri: lb://abeille-secure-server
          predicates:
            - Path=/server/**
          filters:
            - StripPrefix= 1
