##===== routing configuration =====##
spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        #-----------------------------------#
        - id: host_route
          uri: lb://abeille-basic-hypervisor
          predicates:
            - Path=/hypervisor
        #-----------------------------------#
        - id: host_route
          uri: lb://abeille-basic-assets
          predicates:
            - Path=/group