##===== load Eureka registry center =====##
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

##===== server port =====##
server:
  port: 8088

##===== active profiles =====##
spring:
  profiles:
    active: prod
